### ISSUE TITLE
One line request mutation

### ISSUE THREAD

**Issue by siga111** [fullcontact/proxinius#2]
It would be nice to have one line command to set mutation for specific endpoints. It would make easier testing of specific bugs and provide better UX overall.

In typical CLI app it would look something like `proxinius mutate -u "<url>" -m <mutation_id>`. 
Not sure how it looks in clojure, probably with more parenthesis and weird parameter order. :)

**Comment by taubeklavs** [comment]
Added in https://github.com/fullcontact/proxinius/pull/5
