### ISSUE TITLE
Print ip address on startup

### ISSUE THREAD

**Issue by siga111** [fullcontact/proxinius#3]
Would be nice to see full endpoint or at least ip address to connect to when starting proxinius.
It already shows port, but it is only partial information.

Ideally it would be nice to see something like `proxinius running on "http://<ip address>:<port>"` so that it can be copied directly from console to source code.

**Comment by taubeklavs** [comment]
I don't think it's a good idea because a machine can have multiple network interfaces with multiple IP addresses. It could be tricky to determine which one to show. You should use `ifconfig`, or `ip addr` if You are on a modern Linux distro.

**Comment by FnTm** [comment]
Addressed in https://github.com/fullcontact/proxinius/pull/6
